# Generated by Django 3.0.6 on 2020-06-10 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('id_art', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_art', models.CharField(max_length=25, unique=True)),
                ('precio_a', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cant_a', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='asd',
            fields=[
                ('id_asd', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.DecimalField(decimal_places=10, max_digits=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='datos_personales',
            fields=[
                ('id_datos_personales', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('fecha_nac', models.DateTimeField()),
                ('id_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='det_factura',
            fields=[
                ('id_det_factura', models.AutoField(primary_key=True, serialize=False)),
                ('precio_t', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fecha_c', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='detalle_venta',
            fields=[
                ('id_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now=True)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=3)),
                ('cantidad_ventas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='domicilio',
            fields=[
                ('id_domicilio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
                ('id_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.articulo')),
                ('id_det_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.det_factura')),
            ],
        ),
        migrations.CreateModel(
            name='legajo_empleado',
            fields=[
                ('id_legajo_empl', models.AutoField(primary_key=True, serialize=False)),
                ('antiguedad', models.CharField(max_length=5)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('id_datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.datos_personales')),
                ('id_legajo_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.legajo_empleado')),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='rubro',
            fields=[
                ('id_rubro', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_r', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_persona',
            fields=[
                ('id_tpo_persona', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_tpo_p', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('id_detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.detalle_venta')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.factura')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.persona')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='id_tpo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.tipo_persona'),
        ),
        migrations.AddField(
            model_name='det_factura',
            name='id_tpo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.tipo_persona'),
        ),
        migrations.AddField(
            model_name='datos_personales',
            name='id_domicilio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.domicilio'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='id_rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.rubro'),
        ),
    ]
