# Generated by Django 3.0.6 on 2020-06-05 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20200604_2221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='articulos',
            new_name='articulo',
        ),
        migrations.RenameModel(
            old_name='proveedores',
            new_name='proveedor',
        ),
        migrations.RenameModel(
            old_name='rubros',
            new_name='rubro',
        ),
    ]
