# Generated by Django 3.0.6 on 2020-06-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20200605_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='nombre_art',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
