# Generated by Django 3.0.6 on 2020-06-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_auto_20200605_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.DecimalField(decimal_places=10, max_digits=99999999999),
        ),
    ]
