# Generated by Django 3.0.6 on 2020-06-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_auto_20200606_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
